version: 1.0.{build}
build_script:
- cmd: dotnet publish --configuration Release
test_script:
- cmd: dotnet test TileService.Tests
artifacts:
- path: TileService\bin\Release\netcoreapp2.1\publish
